apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: potnt
  name: potnt-frontend-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - potnt.kuly.cloud
      secretName: potnt-frontend-tls
  rules:
    - host: potnt.kuly.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: potnt-frontend
                port:
                  number: 80