apiVersion: v1
kind: Service
metadata:
  namespace: potnt
  name: potnt-frontend
  labels:
    app: potnt-frontend
    tier: frontend
spec:
  ports:
    - port: 80
  selector:
    app: potnt-frontend
    tier: frontend
