name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - release

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: potnt-frontend

jobs:
  push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo${{ secrets.CR_PAT }} | docker login ghcr.io  -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/lucaschimweg/$IMAGE_NAME
          VERSION="latest"

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
